### ISSUE TITLE
 no graph 

### ISSUE THREAD

**Issue by twrjie** [raphaelsty/kgsearch#1]
![image](https://github.com/user-attachments/assets/be2a6340-3df2-40e7-9b6c-743079690631)
Hello, I downloaded kgsearch the way you did, and then ran kg start, but there is no graph in my browser, I also tried to run kg add -f data.csv but the result is still the same

**Comment by twrjie** [comment]
The browser I use is Microsoft Edge

**Comment by raphaelsty** [comment]
Hi @twrjie could you pull the last version and try again ? I think it was related to a three.js update

**Comment by raphaelsty** [comment]
@twrjie It should work fine now: `pip install git+https://github.com/raphaelsty/kgsearch`

**Comment by twrjie** [comment]
I re-downloaded the program and Pip Instalkit + Hetpps://Gitub. Kom/Rafalsti/Kitsek but it still doesn't seem to work

**Comment by raphaelsty** [comment]
Could you share some error code ?

**Comment by twrjie** [comment]
![image](https://github.com/user-attachments/assets/ae6b62e4-eee0-4ffe-9789-2c8dfa2a1d20)
![image](https://github.com/user-attachments/assets/8f06b21c-a887-4053-bd22-8193a093d35b)
![image](https://github.com/user-attachments/assets/5dd6d1cf-a177-4575-b432-d51b9cb0c3b9)
These errors appear to occur when checking the code on the web side

**Comment by raphaelsty** [comment]
Thank you, no error on python side which is cool. The error comes from javascript.
Unfortunately I'm working on Mac and can't download internet explorer to properly test it, could you try the url in firefox? You just have to copy paste the url you did open in internet explorer to view the website in firefox

**Comment by twrjie** [comment]
![image](https://github.com/user-attachments/assets/b6b368a4-44ba-4100-8065-4b68a2ee21c1)
I tried Firefox but it still doesn't seem to work, as you said it might be because of a problem with the three.cjs file

**Comment by raphaelsty** [comment]
Please could you run 

```
pip uninstall kgsearch
```

and then 

```
pip install git+https://github.com/raphaelsty/kgsearch
```

I did not tell before to uninstall kgsearch, but in order to download the last version you need to uninstall it first

**Comment by twrjie** [comment]
![image](https://github.com/user-attachments/assets/01d4f26d-e849-4d00-a2aa-1b1a2fa90785)
You succeeded master, I succeeded in showing, in Chinese it is awesome=牛逼, thank you very much

**Comment by raphaelsty** [comment]
Amazing 🥹❤️
